version: '3.8'

services:
  postgres:
    container_name: money-mind-api
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=money_mind
      - PGDATA=/data/postgres

    volumes:
      - ./data/pg:/data/postgres
