import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Toaster } from "./_components/ui/sonner";
import { Provider } from "./_provider/queryClient";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${mulish.className} dark antialiased`}>
        <Provider>
          <Toaster />

          <ClerkProvider
            appearance={{
              baseTheme: dark,
            }}
          >
            <NuqsAdapter>{children}</NuqsAdapter>
          </ClerkProvider>
        </Provider>
      </body>
    </html>
  );
}
